---
title: "Estadística I, I-2020"
author: "Lic. Alvaro Chirino Gutierrez"
date: "Julio, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,warning=F,message=F}
rm(list=ls())
library(readxl)
library(knitr)
library(dplyr)
#lista oficial
lista<-read_excel("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\Lista-EST 133-2020-PRIMERO-C.xls",range = "A11:I119")
#parcial1
bd<-read_excel("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\NOT_EST-133-I2020.xls")
```


```{r,echo=FALSE}
#parcial2
load("C:\\Users\\ALVARO\\Documents\\GitHub\\notas\\EST133_I2020\\p2rev.RData")
p2r<-p2
rm(p2)
load("C:\\Users\\ALVARO\\Documents\\GitHub\\notas\\EST133_I2020\\p2rev2.RData")
names(p2)[1]<-"CI"
p2$p2_20<-apply(cbind(p2$p2_20,p2r$p2_20),1,max)
rm(p2r)
#length(unique(p2$ci))
#parcial 3
load("C:\\Users\\ALVARO\\Documents\\GitHub\\notas\\EST133_I2020\\p3.RData")
#length(unique(p3$ci))
names(p3)[2]<-"p3_20"
#recuperatorio
load("C:\\Users\\ALVARO\\Documents\\GitHub\\notas\\EST133_I2020\\recup.RData")
#length(unique(recup$ci))
#p1 recup
p1<-bd[,5:6]
names(p1)<-c("ci","p1_20")
aux<-recup[recup$tipo=="Primer parcial",2:3]
#correción
aux[aux$ci=="13440232","ci"]<-"13440292"
p1r<-merge(p1,aux,all.x= T)
p1r$p1r<-apply(p1r[,2:3],1,max,na.rm=T)
#p2 recup
aux<-recup[recup$tipo=="Segundo Parcial",2:3]
names(p2)[1]<-"ci"
p2r<-merge(p2,aux,all= T)
p2r$p2r<-apply(p2r[,2:3],1,max,na.rm=T)
#p3 recup
aux<-recup[recup$tipo=="Tercer Parcial",2:3]
p3r<-merge(p3,aux,all= T)
p3r$p3r<-apply(p3r[,2:3],1,max,na.rm=T)
################################
#Consolidado
#p1
names(p1r)<-c("CI","p1_20","rec_p1","p1_20_final")
names(p2r)<-c("CI","p2_20","rec_p2","p2_20_final")
names(p3r)<-c("CI","p3_20","rec_p3","p3_20_final")
aux<-merge(p1r,p2r,all = T)
#corrección
p3r<-p3r[p3r$CI!="7777777",]
p3r[p3r$CI=="10082977","CI"]<-"10082877"
aux<-merge(aux,p3r,all = T)
#union global
bd2<-merge(bd,aux,all = T)

bd2$`P1/20`<-bd2$p1_20_final
bd2$`P2/20`<-bd2$p2_20_final
bd2$`P3/20`<-bd2$p3_20_final

bd2$`P1/20`[is.na(bd2$`P1/20`)]<-0
bd2$`P2/20`[is.na(bd2$`P2/20`)]<-0
bd2$`P3/20`[is.na(bd2$`P3/20`)]<-0

bd2$PtsExtra[is.na(bd2$PtsExtra)]<-0
#suma global
bd2$Total<-apply(bd2[,6:11],1,sum)
#lista oficial 
lista$CI<-as.numeric(lista$Cedula)

bd3<-merge(lista,bd2,all.x = T)
###########publicar 
oo<-order(bd3$CI)
#kable(bd)
DT::datatable(bd3[oo,c(1,15:21)],style = "bootstrap")
#base para transcribir
bdf<-bd3 %>% arrange(Nro.)
bdf$P1<-bdf$`P1/20`
bdf$P2<-bdf$`P2/20`+bdf$PtsExtra
bdf$P3<-bdf$`P3/20`
bdf$P4<-bdf$`EF/30`
bdf$P5<-bdf$`AYD/10`
bdf<-bdf[,c(1:10,21)]
library(writexl)
write_xlsx(bdf,"C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\notas_finales_I2020.xlsx")
```

# Rendimiento (Todos los estudiantes `r dim(bd3)[1]`)

```{r,echo=FALSE}
hist(bd3$`P1/20`,xlim=c(0,20),main="Parcial 1",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$`P1/20`),col="blue",lwd=2)
hist(bd3$`P2/20`,xlim=c(0,20),main="Parcial 2",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$`P2/20`),col="blue",lwd=2)
hist(bd3$`P3/20`,xlim=c(0,20),main="Parcial 3",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$`P3/20`),col="blue",lwd=2)
```

# Rendimiento (Sin contar abandonos `r dim(bd3[bd3$Total!=0,])[1]`)

```{r,echo=FALSE}
aux<-bd3$Total!=0
hist(bd3$`P1/20`[aux],xlim=c(0,20),main="Parcial 1",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$`P1/20`[aux]),col="blue",lwd=2)
hist(bd3$`P2/20`[aux],xlim=c(0,20),main="Parcial 2",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$`P2/20`[aux]),col="blue",lwd=2)

hist(bd3$`P3/20`[aux],xlim=c(0,20),main="Parcial 3",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$`P3/20`[aux]),col="blue",lwd=2)

hist(bd3$Total[aux],xlim=c(0,100),main="Nota Acumulada",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd3$Total[aux]),col="blue",lwd=2)
plot(density(bd3$Total[bd3$Total!=0]),main="Distribuición de la nota final")
```