---
title: "Estadística I, II-2020"
author: "Lic. Alvaro Chirino Gutierrez"
date: "Diciembre, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,warning=F,message=F}
rm(list=ls())
library(readxl)
library(knitr)
library(dplyr)
#lista oficial
lista<-read_excel("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\Lista-EST 133-2020-SEGUNDO-C.xls",range = "A11:J113")
#parcial1
load("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\r-exams\\p1_ii2020.RData")
p1<-p1_fin
################################
#Consolidado
#ci
ci<-lista[,c(3,4)]
names(ci)[1]<-"ci"
#P1
p1_ci<-merge(ci,p1,all = T)
p1_ci<-p1_ci[,c(1,7:21)]
names(p1_ci)[1]<-"Cedula"
p1_ci$tipo[p1_ci$tipo==10 & !is.na(p1_ci$tipo)]<-0
#union global
bd<-merge(lista,p1_ci[,c("Cedula","nota_P1")],all.x = T)
bd$nota_P1[is.na(bd$nota_P1)]<-0
bd$P1<-bd$nota_P1
bd$Total<-apply(bd[,5:10],1,sum)
################################
################################
#parcial2
load("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\r-exams\\p2_ii2020.RData")
p2<-p2_fin
################################
#Consolidado
#P1
p2_ci<-merge(ci,p2,all = T)
p2_ci<-p2_ci[,c(1,7:16)]
names(p2_ci)[1]<-"Cedula"
p2_ci$tipo[p2_ci$tipo==10 & !is.na(p2_ci$tipo)]<-0
#union global
bd<-merge(bd,p2_ci[,c("Cedula","nota_P2")],all.x = T)
bd$nota_P2[is.na(bd$nota_P2)]<-0
bd$P2<-bd$nota_P2
###############################
#Tareas virtuales y práctica
###############################
tarea<-read.csv("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\r-exams\\EST_133_C_ESTADÍSTICA_I.csv")
tarea<-tarea[-c(1:2),]
names(tarea)<-c("apellido","name","mail",paste0("tarea",1:12),"practica")

tarea[,4:16] <- sapply(tarea[,4:16],as.numeric)
tarea[is.na(tarea)]<-0

tarea$nota_P3<-apply(tarea[,4:15],1,sum)
tarea$nota_P5<-tarea$practica
tarea<-tarea %>% filter(nota_P3>0 | nota_P5>0)
#mail
mail<-read_excel("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\r-exams\\mail_EST133_II2020.xlsx",range = "D11:F113")
names(mail)<-c("Cedula","Nombre","mail")
tarea2<-merge(mail,tarea,all.y = T)

auxci<-read_excel("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\r-exams\\data_ci.xlsx")
tarea3<-merge(tarea2,auxci,all.x = T)
tarea3$Cedula[is.na(tarea3$Cedula)]<-tarea3$CI[is.na(tarea3$Cedula)]

tarea3<-tarea3 %>% group_by(Cedula) %>% summarise(nota_P3=max(nota_P3),nota_P5=max(nota_P5))
#aux<-tarea2[is.na(tarea2$Cedula),1:4]$mail
#write.xlsx(tarea2[is.na(tarea2$Cedula),1:5],"data.xlsx")
###############################
### Recuperatorio
###############################
load("C:\\Users\\ALVARO\\Box\\2020\\umsa\\est133\\r-exams\\recup.RData")
names(recup)<-c("tipo","Cedula","nota_recup")
bd<-merge(bd,tarea3,all.x = T)
bd<-merge(bd,recup,all.x = T)

bd$nota_P3[is.na(bd$nota_P3)]<-0
bd$nota_P5[is.na(bd$nota_P5)]<-0
bd$nota_recup[is.na(bd$nota_recup)]<-0
bd$tipo[is.na(bd$tipo)]<-""

bd$P1[bd$tipo=="Primer parcial"]<-pmax(bd$P1[bd$tipo=="Primer parcial"],bd$nota_recup[bd$tipo=="Primer parcial"])

bd$P2[bd$tipo=="Segundo Parcial"]<-pmax(bd$P2[bd$tipo=="Segundo Parcial"],bd$nota_recup[bd$tipo=="Segundo Parcial"])

bd$P3<-bd$nota_P3
bd$P5<-bd$nota_P5

###############################

bd$Total<-apply(bd[,5:10],1,sum)

###########publicar 
oo<-order(bd$Cedula)
#kable(bd)
```

# Consolidado por evaluación

* P1: Parcial 1
* P2: Parcial 2
* P3: Trabajos virtuales
* P4: Final
* P5: Práctica
* P6: Poster

```{r,echo=FALSE,warning=F,message=F}
DT::datatable(bd[oo,c(1,5:10,12)],style = "bootstrap")
```

## Patrón de respuesta Parcial 1

```{r,echo=FALSE,warning=F,message=F}
DT::datatable(p1_ci,style = "bootstrap")
```

## Patrón de respuesta Parcial 2

```{r,echo=FALSE,warning=F,message=F}
DT::datatable(p2_ci,style = "bootstrap")
```

## Solucionario Parcial 1

último dígito CI | Respuestas
------|---------
0 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_00.pdf)
1 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_01.pdf)
2 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_02.pdf)
3 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_03.pdf)
4 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_04.pdf)
5 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_05.pdf)
6 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_06.pdf)
7 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_07.pdf)
8 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_08.pdf)
9 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p1_sol_09.pdf)

## Solucionario Parcial 2

último dígito CI | Respuestas
------|---------
0 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_00.pdf)
1 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_01.pdf)
2 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_02.pdf)
3 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_03.pdf)
4 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_04.pdf)
5 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_05.pdf)
6 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_06.pdf)
7 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_07.pdf)
8 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_08.pdf)
9 | [Aquí](https://alvarolimber.github.io/notas/EST133_II2020/p2_sol_09.pdf)

# Rendimiento (Todos los estudiantes `r dim(bd)[1]`)

```{r,echo=FALSE}
hist(bd$P1,xlim=c(0,20),main="Parcial 1",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P1),col="blue",lwd=2)

hist(bd$P2,xlim=c(0,20),main="Parcial 2",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P2),col="blue",lwd=2)
```

# Rendimiento (Sin contar abandonos `r dim(bd[bd$Total!=0,])[1]`)

```{r,echo=FALSE}
aux<-bd$Total!=0
hist(bd$P1[aux],xlim=c(0,20),main="Parcial 1",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P1[aux]),col="blue",lwd=2)

hist(bd$P2[aux],xlim=c(0,20),main="Parcial 2",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P2[aux]),col="blue",lwd=2)

library(ggplot2)
ggplot(bd[aux,],aes(Total))+geom_density(colour="red")+title("Total")
```