---
title: "Estadística II, I-2021"
author: "Lic. Alvaro Chirino Gutierrez"
date: "I-2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,warning=F,message=F}
rm(list=ls())
library(readxl)
library(knitr)
library(dplyr)
#lista oficial
lista<-read_excel("C:\\Users\\ALVARO\\Box\\2021\\umsa\\EST145\\lista.xls")
#parcial1
load("C:\\Users\\ALVARO\\Box\\2021\\umsa\\EST145\\r-exams\\notasP1.Rdata")
p1<-datavf
#parcial2
load("C:\\Users\\ALVARO\\Box\\2021\\umsa\\EST145\\r-exams\\notasP2.Rdata")
p2<-datavf
################################
#Consolidado
#ci
ci<-lista[,c(3,4)]
names(ci)[1]<-"ci"
#######################
#P1
p1_ci<-merge(ci,p1,all = T)
p1_ci<-p1_ci[,c(1,8:19)]
names(p1_ci)[1]<-"Cedula"
names(p1_ci)[13]<-"nota_P1"
p1_ci$tipo[p1_ci$tipo==10 & !is.na(p1_ci$tipo)]<-0
#union global
names(lista)[3]<-"Cedula"
bd<-merge(lista,p1_ci[,c("Cedula","nota_P1")],all.x = T)
bd$nota_P1[is.na(bd$nota_P1)]<-0
bd$P1<-bd$nota_P1
#######################
#P2
p2_ci<-merge(ci,p2,all = T)
p2_ci<-p2_ci[,c(1,8:18)]
names(p2_ci)[1]<-"Cedula"
names(p2_ci)[12]<-"nota_P2"
p2_ci$tipo[p2_ci$tipo==10 & !is.na(p2_ci$tipo)]<-0
#union global
bd<-merge(bd,p2_ci[,c("Cedula","nota_P2")],all.x = T)
bd$nota_P2[is.na(bd$nota_P2)]<-0
bd$P2<-bd$nota_P2

#bd$Total<-apply(bd[,5:10],1,sum)

###########publicar 
oo<-order(bd$Cedula)
#kable(bd)
writexl::write_xlsx(bd,"C:\\Users\\ALVARO\\Box\\2021\\umsa\\EST145\\r-exams\\consolidado_v0.xlsx")
```

# Consolidado por evaluación

* P1: Parcial 1
* P2: Parcial 2

```{r,echo=FALSE,warning=F,message=F}
DT::datatable(bd[oo,c(1,8,10)],style = "bootstrap")

#bd %>% mutate(Estado=if_else(Total>50,"Aprobado","Reprobado")) %>% group_by(Estado) %>% count() %>% kable()
```

## Patrón de respuesta Parcial 1

```{r,echo=FALSE,warning=F,message=F}
DT::datatable(p1_ci,style = "bootstrap")
```

## Solucionario Parcial 1

último dígito CI | Respuestas
------|---------
0 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_00.pdf)
1 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_01.pdf)
2 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_02.pdf)
3 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_03.pdf)
4 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_04.pdf)
5 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_05.pdf)
6 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_06.pdf)
7 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_07.pdf)
8 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_08.pdf)
9 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p1_sol_09.pdf)

## Patrón de respuesta Parcial 2

```{r,echo=FALSE,warning=F,message=F}
DT::datatable(p2_ci,style = "bootstrap")
```

## Solucionario Parcial 2

último dígito CI | Respuestas
------|---------
0 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_00.pdf)
1 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_01.pdf)
2 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_02.pdf)
3 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_03.pdf)
4 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_04.pdf)
5 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_05.pdf)
6 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_06.pdf)
7 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_07.pdf)
8 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_08.pdf)
9 | [Aquí](https://alvarolimber.github.io/notas/EST145_I2021/p2_sol_09.pdf)

# Rendimiento (Todos los estudiantes `r dim(bd)[1]`)

```{r,echo=FALSE}
hist(bd$P1,xlim=c(0,30),main="Parcial 1",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P1),col="blue",lwd=2)

hist(bd$P2,xlim=c(0,30),main="Parcial 2",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P2),col="blue",lwd=2)

plot(bd$P1,bd$P2,xlim=c(0,30),ylim = c(0,30),main = "Relación P1 vs P2",xlab="Parcial 1",ylab="Parcial 2")
```

# Rendimiento (Sin contar abandonos `r dim(bd[bd$Total!=0,])[1]`)

```{r,echo=FALSE}
aux<-bd$P1!=0
hist(bd$P1[aux],xlim=c(0,30),main="Parcial 1",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P1[aux]),col="blue",lwd=2)

aux<-bd$P2!=0
hist(bd$P2[aux],xlim=c(0,30),main="Parcial 2",xlab="Nota",ylab="Estudiantes")
abline(v=mean(bd$P2[aux]),col="blue",lwd=2)

#library(ggplot2)
#ggplot(bd[aux,],aes(Total))+geom_density(colour="red")+title("Total")
```